name: ci-go_sonarcloud
on:
  pull_request:
    branches:
      -develop

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - run: go test -coverprofile=coverage.out